# **Installation of NumPy**


```
pip install numpy
```



In [2]:
#علامة التعجب بالكولاب تعني ان هذا السطر هو امر تنفيذ لينكس و ليس بايثون كود
!pip install numpy
!pwd #كود لينكس معناته انا في اي دايريكتوري موجود حاليا

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
/content


# **NumPy as np**

```
import numpy as np
```



In [5]:
import numpy as np


# **Creating Arrays**

```
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))
```



In [9]:
import numpy as np
arr1 = [1, 2, 3, 4, 5]
print(type(arr1))
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2)
print(type(arr2))

<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in Arrays
0-D Arrays


```
import numpy as np

arr = np.array(42)

print(arr)
```



In [10]:
import numpy as np
arr = np.array(42)
print(arr)

42


# 1-D Arrays


```
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
```



In [11]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


# **2-D Arrays**


```
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
```



In [12]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


# **3-D arrays**

```
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
```



In [13]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# **Check Number of Dimensions?**


```
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
```



In [14]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# **NumPy Array Indexing**


```
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
```



In [19]:
import numpy as np

arr = np.array([
    [
        [1, 2, 3],
      [4, 5, 6]
     ],

     [
         [7, 8, 9],
       [10, 11, 12]
      ]
      ]      )

print(arr[1, 1, 2])

12


# **NumPy Array Slicing**


```
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])
```



In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


# **Slicing 2-D Arrays**


```
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
```



In [30]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 2:4])
print(arr[0, 1:3])

[8 9]
[2 3]


In [74]:
mtr = np.random.rand(50,100)
print(mtr.min())

9.129811928421105e-05


In [79]:
a = np.array([1,2,3])
b = a # copy by reference 
print(b)

a[1]=15
print(b)

[1 2 3]
[ 1 15  3]


In [81]:
a = np.array([1,2,3])
b = np.copy(a) # copy by value
print(b)

a[1]=15
print(b)

[1 2 3]
[1 2 3]


In [83]:
a = np.array([565,5555,6565637456,32452345,1211,123234,43563456,786789789,21312,3333,544,53245,2345,2234523])
print(np.sort(a,))

[       544        565       1211       2345       3333       5555
      21312      53245     123234    2234523   32452345   43563456
  786789789 6565637456]


In [93]:
a = np.array([[1,2,3],[1,2,3]])
b = np.array([[4,5,6],[4,5,6]])
c= np.concatenate((a,b),axis=1)
print(c)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [97]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
b = np.array([[4,5,6],[4,5,6],[4,5,6]])

c=np.dot(a,b)

print(c)

c=np.multiply(a,b)

print(c)

[[24 30 36]
 [24 30 36]
 [24 30 36]]
[[ 4 10 18]
 [ 4 10 18]
 [ 4 10 18]]
